package JTestP;

import java.io.File;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Base64;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pamelagarcia
 */
public class Login extends javax.swing.JFrame {

    String passwd;
    String user;
    String[] temp;
    File f;
    FileWriter fout;
    BufferedReader fin;
    HashMap<String, String> fields = new HashMap<String, String>();
    HashMap<String, String> credenciales = new HashMap<String, String>();
    int i = 0;
    String line, usr, pass;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logIn = new javax.swing.JDialog();
        logUsuario = new javax.swing.JTextField();
        usuarioEt = new javax.swing.JLabel();
        passwordEt = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        logPassword = new javax.swing.JPasswordField();
        signIn = new javax.swing.JDialog();
        signUsuario = new javax.swing.JTextField();
        usuarioEt2 = new javax.swing.JLabel();
        passwordEt2 = new javax.swing.JLabel();
        registrarButton = new javax.swing.JButton();
        cancelarButton2 = new javax.swing.JButton();
        signPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        logIn.setTitle("Ingresar");
        logIn.setMinimumSize(new java.awt.Dimension(270, 170));
        logIn.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        usuarioEt.setText("Usuario:");

        passwordEt.setText("Contraseña:");

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        logPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInLayout = new javax.swing.GroupLayout(logIn.getContentPane());
        logIn.getContentPane().setLayout(logInLayout);
        logInLayout.setHorizontalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logInLayout.createSequentialGroup()
                        .addComponent(cancelarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(aceptarButton))
                    .addGroup(logInLayout.createSequentialGroup()
                        .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordEt)
                            .addComponent(usuarioEt))
                        .addGap(18, 18, 18)
                        .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(logPassword))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        logInLayout.setVerticalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioEt)
                    .addComponent(logUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordEt)
                    .addComponent(logPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(cancelarButton))
                .addGap(30, 30, 30))
        );

        signIn.setTitle("Registrar");
        signIn.setMinimumSize(new java.awt.Dimension(270, 170));
        signIn.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        signUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUsuarioActionPerformed(evt);
            }
        });

        usuarioEt2.setText("Usuario:");

        passwordEt2.setText("Contraseña:");

        registrarButton.setText("Registrar");
        registrarButton.setToolTipText("");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        cancelarButton2.setText("Cancelar");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInLayout = new javax.swing.GroupLayout(signIn.getContentPane());
        signIn.getContentPane().setLayout(signInLayout);
        signInLayout.setHorizontalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signInLayout.createSequentialGroup()
                        .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordEt2)
                            .addComponent(usuarioEt2))
                        .addGap(18, 18, 18)
                        .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(signPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signInLayout.createSequentialGroup()
                        .addComponent(cancelarButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(registrarButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        signInLayout.setVerticalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioEt2)
                    .addComponent(signUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordEt2)
                    .addComponent(signPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarButton)
                    .addComponent(cancelarButton2))
                .addGap(30, 30, 30))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Sign up");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        logIn.setLocationRelativeTo(this);
        logIn.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
        passwd = new String (logPassword.getPassword());
        user = logUsuario.getText();
        f = new File("credenciales.txt");
        StringBuilder strb = new StringBuilder();
        
        if(f.exists()){
            try{
                fin = new BufferedReader(new FileReader(f));
                while ((line = fin.readLine()) != null){
                    temp = line.split(":", 2);
                    if(temp.length >= 2){
                        usr = decrypt(temp[0]);
                        pass = decrypt(temp[1]);
                        credenciales.put(usr, pass);
                        
                    }
                }
                fin.close();
            }catch(IOException e){}
        }
        
        else{
            JOptionPane.showMessageDialog(logIn, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            logUsuario.setText("");
            logPassword.setText("");
        }
        
        if(credenciales.containsKey(user)){
            if(passwd.equals(credenciales.get(user))){
                JOptionPane.showMessageDialog(logIn, "Ingresando a su cuenta.", "Exito", JOptionPane.INFORMATION_MESSAGE); 
                logIn.dispose();
                
                
                frmTest test = new frmTest(user);
                
                test.setVisible(true);
                this.dispose();
                
                
            }
            else
                JOptionPane.showMessageDialog(logIn, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                logPassword.setText("");
        }
        else
            JOptionPane.showMessageDialog(logIn, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            logUsuario.setText("");
            logPassword.setText("");
        
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        // TODO add your handling code here:
        passwd = new String(signPassword.getPassword());
        user = signUsuario.getText();
        fields.put(user, passwd);
        f = new File("credenciales.txt");
        StringBuilder strb = new StringBuilder();
        
        if(f.exists()){
            try{
                fin = new BufferedReader(new FileReader(f));
                while (fin.ready()){
                    strb.append(fin.readLine()).append(System.lineSeparator());
                }
                fin.close();
            }catch(IOException e){}
            strb.append(encrypt(user)).append(":").append(encrypt(fields.get(user))).append(System.lineSeparator());
        }
        
        else{   
            for (String k : fields.keySet())
                strb.append(encrypt(k)).append(":").append(encrypt(fields.get(k))).append(System.lineSeparator());
        }   
        
        try{
            fout = new FileWriter(f);
            fout.write(strb.toString());
            fout.flush();
            fout.close();
        }catch(IOException e){}
        JOptionPane.showMessageDialog(signIn, "Usuario registrado.", "Exito", JOptionPane.INFORMATION_MESSAGE); 
        signUsuario.setText("");
        signPassword.setText("");
        signIn.dispose();
        
    }//GEN-LAST:event_registrarButtonActionPerformed
    
    public String encrypt(String info){
        byte[] bit = info.getBytes();
        String encrypted;
        encrypted = Base64.getEncoder().encodeToString(bit);
        return encrypted;
    }
    
    public String decrypt(String info){
        byte bit[] = Base64.getDecoder().decode(info);
        String decrypted = new String(bit);
        return decrypted;
    }
    
    private void signUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUsuarioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        signIn.setLocationRelativeTo(this);
        signIn.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        // TODO add your handling code here:
        signIn.setVisible(false);
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        logIn.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void logPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog logIn;
    private javax.swing.JPasswordField logPassword;
    private javax.swing.JTextField logUsuario;
    private javax.swing.JLabel passwordEt;
    private javax.swing.JLabel passwordEt2;
    private javax.swing.JButton registrarButton;
    private javax.swing.JDialog signIn;
    private javax.swing.JPasswordField signPassword;
    private javax.swing.JTextField signUsuario;
    private javax.swing.JLabel usuarioEt;
    private javax.swing.JLabel usuarioEt2;
    // End of variables declaration//GEN-END:variables
}
